apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
spec:
  ingressClassName: ingress-nginx-internal
  tls:
    - hosts:
        - immortalkeep.com
      secretName: demo-ingress-tls
  rules:
  - host: immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: homepage
            port:
              number: 3000
