apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
type: Opaque
stringData:
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:OtkVm+lb50+MT2g2rsF0k47OEx8=,iv:KOxbe1RHm2+7bUmHCP99SBcRT3Uh0TjObJQd1+y6bmY=,tag:6QskSdirgXR+ckd91PHnbA==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_KEY: ENC[AES256_GCM,data:e+yheYE8EV1XXWW3oRhFM9gQUMy9rwCBFCT8,iv:PZ4f5GCD1I8k6cy6zh1PtwnGig+NUB5TlKVRo5plPl0=,tag:McEhJk+OlQ7Qaf06bFcbHw==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:xB+fDRA=,iv:Y/1in4DXBujKDOqY5RtwKesjv/o2jbsKnPC7mlP1j3g=,tag:ir65ldkIDVmo9nI8g1UwaQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:XiyqxLbwyJD47LtVJw==,iv:kjdhgu7WpSxo4KXfitteQJfFr8ibchhILvwuaTovpYA=,tag:0P3UVBIIC180esz1112uag==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBRekg5
            VFIybVV0MmlRcGtrOHkyUVZWQW1zUkxIeGRTODVZZndocTdmcUZNCjlXQ3V2Szdy
            aC8vMytGV2tzK0t0SnRmV1d0Z00vdUp4dEtBMElYWmhHcmcKLS0tIDAySU5mY2ZC
            anRsOVA3b3dYMUFtWXRvcjBBb2hGZ205UHJ1S0lsb3IxYWsK+/UT7KJ5aEh9uW3X
            GgpJu1yhZThB3r5HvXa+gQLhdrQvgCUc5e3zMc/9ajg6r+2aEQJxoxQAuYHN0/oC
            U8upVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBBLzI0
            dGVTcGdoSlg1NUpKYWpMVy90TFMxbjVmQzQyNmZWaFRSWXhCdXc4Cm1DbUxKSzEz
            NUEvMTEwMXNUOWQ4ZzR6ZnNmT0VOTHBtMDExMWJMbnBzOXMKLS0tIGhxclNGenBF
            M24zSjIyUzlJZU9saVpTNXE2VVpwZ053VjF3S3EwL0RGYVkKDOrF4OADi8NjY0ah
            rOtFOyKfA/3Pjx348kDo9bdhWJXUN+47BC0gNtVfJ/y/8lSJQ3GH9k7EH/O0hXdp
            KhFIfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWTE4TlZJYmsrWDJNYitv
            WGdiMkxpL3VXc2Y3Q09ubmh2K1FXWW1NUUdBCmxBeTR4QWpQNXNYYm5CVkh0NTA2
            Q0RDWEk4RG5LekVKRUQ0M0ZsMnNyN28KLS0tIDdJOVR6ay9uNTlFekppQ1RBNXQz
            QXN0ayswWDQ1elZaMEJwYkFjbnVzcG8K85hS3qepCfIW23ZjbpOSmyx4ALN3B3iU
            Uc147jJdqjgS40pUlknLi+x9FLTRANau7xXxrFh0Xg8pJffZ6BtAwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T05:41:10Z"
    mac: ENC[AES256_GCM,data:5eLeGMi7ZcRGm7CCUJox3N1b/RgXQjOZwOssocIq0XN9NBHGgggSXL6pBjtnzEuGY3M8s7M2iSK9/SuA7tH7hxtKPFEbt4EK85smC6zJzJMcM0t/b1WHi+KoMvukOVGaZNFPZd9kP2UEjFCwcI/12GRV+S866R1n2nKDPfzIIbY=,iv:WcOz/lVoZwRpbLUG/uuf/v/mso1zbgAm+coIPxM4jPU=,tag:ZEFgtMrnqU5I3Qq4CuQ6Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
