apiVersion: v1
kind: Secret
metadata:
    name: k8up-repository
    namespace: automatic-ripping-machine
stringData:
    repository-password: ENC[AES256_GCM,data:4B57qd64m1AD+y7vNKklhf7wGmFRqY4C9u7uLKmuBMSGk30KWpfiqVBRxQ==,iv:Q0Jc31R+f6rcHcX+2VhodcRyGpG1FVvXl8nm7CNR/Ak=,tag:BZblo4mEUV73D9ALUJQ8vA==,type:str]
    rest-username: ENC[AES256_GCM,data:8JxyMw==,iv:xbAwSvEDdjkp2SSdCBRgAr6n/kxa33lLUuJSxMMoBnM=,tag:VFpMMt0uYeLDM7znMrtgnA==,type:str]
    rest-password: ENC[AES256_GCM,data:4cQUY05jTVs3aQPFppGXRVX0MzHP8E4sjO/1W/aotOQ=,iv:0GN3uMTEGvtD5Tu8pbV6MbQ9DJpW5LqI4NVb6NC6860=,tag:Or6LXCDYalJM3DXASKhzsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBLT20r
            TDByVVNZejlKbEZVUVl0YzFOMFRUbVl5eW1TYkx0VzVSSEt4Z1Q4CjJBK3pHOWFz
            SGtmNXM0SjNwTm9vdWJsTjh0ejArRUtWZFBLQzZNK3hubU0KLS0tIDNPRlJmTVVo
            c2RSU2FtTUUyUCt2Y3lHWGFaa1MxcVoxazJuNnc0VjVCZUkKfCOKQG3lxvPYSBn/
            8zYp/j8xmS6ep6X48sKe8Pnbc2hZ8YSWIJpiAgeW5V5kwgO2irkYaVL2H9Lz8QUp
            9ewpdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBYM3lu
            RHl2OHhrZ3VmcG9mOTRRUlZqcTI2SUFsaXEvcUlqUDcrQTBJU1I0CkZUQjVVZE5u
            YVgzN29NUHFRbG9FaVdwaGkzQ1JTRWV5OWp0WTMwamFzR3cKLS0tIEZRMXd1MnI2
            eHhQWmVaYjlobU9JbkRmQXZWR2hEbURFWjdjK0hrQkRrZU0Kk/2XkIcslv3uR7ox
            /WgWZVyfSlsAYnuvWVi/YGdpkiX7GoIXVJyOfUqVrN/2tJ/h3bCdFvxzpntHAqnv
            yAG97Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZk44c01jMWErZG0xc2px
            MVNDaW9PQ0V2MUlJWHFKeHBBYjZkZDFaZHdBCmtvczNTbnNRdnpNUVFSeHFBZkdC
            c3pzRjdQUGdDaUdEMjhMNHhBc3VhVDgKLS0tIE5FR0FjejJSSDA5aVNadFI0SEFk
            dkU2TEg5alpKaVI0ZVZ1aENFVnlDcncKcLKHpD8hWCc+8QeXe4Gby73sbjJ3HdfO
            PITXQMQFdH1KZfnzHkyB4yMY6NilB/FR/uZdRWzXtJttHxtYy3/7Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T14:13:25Z"
    mac: ENC[AES256_GCM,data:sPnJH42XB0cHw6BNZH12HTxCMAXgKLCHGBQbEMuYYgtJ2HovYItwWQzWdU7XJTZm+LzwAP9ZG2seTwntdk33TDZ6j0QqPT//PjftPaudRHq0AikMvHSR7KYh8ADavZHM2ZBVVNeBEDkH4ZNHDA57vq2A74hZQWGJbbuPggqXZ8g=,iv:VQRqhqmccZLjDi1n4Cb2exjoFduhQrbm1+sWfu56tSQ=,tag:5fufA4ztG7KB5jo5XCOR9A==,type:str]
    version: 3.13.3
