apiVersion: v1
kind: Secret
metadata:
    name: k8up-repository
    namespace: apps
stringData:
    repository-password: ENC[AES256_GCM,data:4+1ijbow1wLWJGoQJ1kHWhZZbg4jaR7KI3ln5/82UwB4W5bzUsTSW2iOMA==,iv:4/8PMB4/vr/XYTYM4wDN/W+cDS8nlLhtVOr4n8fsJAw=,tag:soYKTtAE18jF3Uf1hIC8PQ==,type:str]
    rest-username: ENC[AES256_GCM,data:viKGNA==,iv:slwo+SFEXFV78kxKQxG5Qb24ZOzrOLOdIBTRGBjsBbU=,tag:MZcE81WDibpY+4HXifi/Lw==,type:str]
    rest-password: ENC[AES256_GCM,data:ol9MvJRoTTnUEt1nvCByrIcoPLQk5RMlHrky/GxblKo=,iv:0S+GB5bVkwwovmmGPfqlmq2q9mFdRbR6eM2/5mJ3hko=,tag:wIbvpan8yLfBBZhenq49iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBJUTAw
            N0d1ckdDa1VhVlNLa0h2blhubUFCRWh2a1R4a2JtQTM1Rno1ckYwClIrak1abEp6
            S0Y2cXZ3YnlBdUREOFNSTlNRRVJOZ0gwVUcvNktTU1BJZ1kKLS0tIGYxcUtORWN5
            K2g2OUlqYjhBZitFb3Y2dkwySWtmS09aM3U0ejFoRWUweVEKC1SgRzIQU4JouVPt
            UN79yT2zVNtxdztFH/bRu694RdVzMPoxiI5k/6/RHcHa59KqtRLx738BPsAvjRxV
            +q+vsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSB1cHlG
            WllsNUh6ZEhXZE43aTdRUkFyaU5WUFcxbVhNbk9JZGc1OGcxRkZFCkRiNFUrRzNQ
            NGd1M3hKR0prZGNBRVBmUjhibXlqemlDR1dCVGxDM003d3cKLS0tIGVBbkFrMkNs
            ZTd5KzdsVXFNanNDU3dGL2xNOE1qZ3IwRkE2bHZNWmg1ZXMKmLI99btoi/lC+2zX
            GWqDzDG4Z8pSOxYdwNLbvt5APDx6A6WEMRQwK7VvkRszhzaBxCHFMLfiRd2TxgjR
            uYnVeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdFhYbHRBbnRCYVA2M2lX
            QTFpOEk4RU9yVVRrY2VzVnZVVit0WU15QWtFCmZnUmpRU2JxeG8rUWwxWWF5WkxN
            b0lZK1BJUVhYZmNDWmoxNDl0Wk0yeDQKLS0tIFV2TzZvQWpRZmNVTi9CY1VQNmUz
            RUNRbGZwWCtVVmFxMy9admhOMndyMDgKC6F4+e8orDM7SfQkurhfZ+hWuqJpIAa6
            Yrk25C0QjXVZ6HP5QWmM0YtLziBQqPrf3ZpzVmFGau/xcuJJ88WHzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T14:13:25Z"
    mac: ENC[AES256_GCM,data:+oLgWoY6mWlTj7UTBBzg5qA2TlNgxEurUo556FRQHc6t+CHsV5cigMBkkTY24H+NH4gv4c4GOG8CczZijmXOUytoS+elpcyu4AMmoTNF3IcoB+09UJS44mJ5AE86+4yEDQH/eXev8L78pLdR4Zz90dLJdlp+O8vIoprlq02kQIA=,iv:zW41M80ZulKmC7KwQGX+bcSN+Wze5le7oYV85fFHHVs=,tag:M5NnR/DqxFdQF8L3PwI1xw==,type:str]
    version: 3.13.3
