apiVersion: v1
kind: Secret
metadata:
    name: k8up-repository
    namespace: infrastructure
stringData:
    repository-password: ENC[AES256_GCM,data:rPhErDbgz7+m5OEg1o/UdyX2dF1rRdEOhWTWjKXhK4hSvgsOVUjRae4+KA==,iv:GayHLoxV4QHbkPxjtmX7MVaoaC7L77rjwJeidyk5wCk=,tag:RqAuFaVGeookuxEUPSBvkg==,type:str]
    rest-username: ENC[AES256_GCM,data:HyqjOg==,iv:W8Ru+IHTcwdUkEYrOaNk9fToAUJzN9vMlD6d+glyYXw=,tag:cHSAOrIZ6zlhYpQv35WDrw==,type:str]
    rest-password: ENC[AES256_GCM,data:DXJOaWXa1eVMHE+Oq6Tk+9OL8lDlCdRaCuuuB9F8mNg=,iv:UST6e05COlqft1O0xkrJiAj8Y7xSCkfhzVSSKeaYGMw=,tag:tHQw+BmqIu2Jux4FBFawBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBkK1Ur
            dVpieTBkSThpejRWWS9zWjZOUU9aQWV1a3lmd2ZSVHBCdVQ0QlVVClNRQzl2d2tF
            bUltL2xJbTliVEJtWFpFRW12S284VW1rWXp3KzVrUFE1dWsKLS0tIDZTYkFaVzlq
            NkNVbU9nSlFhOEFQNmVMMUd6SHlDV3FTOTZkZDE2TjNiekUKvto7rMfhLFSXabm4
            ZVi0n84LZsm+RpYK1Uoyg5QQPxZPcCZsCoUsKF4DwJJw8a7gPdCRNIw2UH8moWFe
            IiB1BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBMZkRF
            MFRYL3RrS3kyQU1GaXVJVnpTTVo4R0JKNmN2UkcvakViS3FBeXdZCkNXcWxPWWsv
            VjVacFcwdnhwQlNvZFVWWnNzN0FNalhRK2N5UE9iSzhLd2sKLS0tIFFIZURZeHEx
            OTJiL0RlOFBWRnJJejdaZ3VUdjdJMklqU3Zka2Y3aTlVczgKUJkPWFUJjDwt3j86
            9LaSmeH14SeSwKwoErK09lUcLfVEQLKas8CHIsJ4pUO6V0HSja2ljd78Vhg/a45g
            Y9EFuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdU9PNVNKVzdpSW45dHAy
            Q1FYL3BVYlk0RzdrWTB0b050SHZhbDcwYUFRCklyVWdEd0E0dndUaG0wZWwyRm1j
            ZFpmUDlHL05HWVkwYThvVitvb20rTVUKLS0tICs1MUxXT2h5YTM3ZDh0c2tnUjVn
            Yyt6MDlTU1doM3ZHN3RldHlTWTBhV0UKiCANR80+CB8XkdJOAPge94SSexLG93AG
            20aC0jcBWolePyfD0iRfD33N3eYXZO6j+GH+K/fFgtN5xEdei96qlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T14:13:25Z"
    mac: ENC[AES256_GCM,data:7AaYs8nGPPm04ZGciCmahdD3OQeeHsBmMz+yTwao4kICHWr8XJNWIq4WkUnOz+hplAPQmlcFECGqb76J1ZSOREMS3Zmq1GM9daM8Ftq9VBE+6Ronze93H6blpq3pKwurjz5y4OotxJfxPKcLBUiLefE2xfe/oDNvi6xIPTaWb6k=,iv:NHkLYE9POyRXqG7lHAO4CChGeDq4bMBzOAZQWCaIP94=,tag:wN/ik85cgBf3JT2gRH2CbQ==,type:str]
    version: 3.13.3
