all:
  children:
    proxmox:
      hosts:
        192.168.0.111:
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    wireguard:
      hosts:
        # 10.0.1.1:
        192.168.0.103:
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    fileserver:
      hosts:
        192.168.0.105:
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
