---
- name: 'set up Wireguard host'
  hosts: wireguard
  vars:

  tasks:
    - name: install wireguard package
      apt:
        name: wireguard
        update_cache: yes
        state: present

    - name: generate Wireguard keypair
      shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
      args:
        creates: /etc/wireguard/privatekey
      become: yes

    - name: register private key
      shell: cat /etc/wireguard/privatekey
      register: wireguard_private_key
      changed_when: false
      become: yes

    - name: register public key
      shell: cat /etc/wireguard/publickey
      register: wireguard_public_key
      changed_when: false
      become: yes

    - name: create server wireguard configuration
      template:
        dest: /etc/wireguard/wg0.conf
        src: server_wg0.conf.j2
        owner: root
        group: root
        mode: '0600'
      notify: reload wireguard config

    - name: enable and persist ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: yes
        reload: yes

    - name: start wireguard and enable on boot
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

  handlers:
  - name: reload wireguard config
    shell: wg syncconf wg0 <(wg-quick strip wg0)
    args:
      executable: /bin/bash
