apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsomatic
  labels:
    app: dnsomatic
spec:
  selector:
    matchLabels:
      app: dnsomatic
  template:
    metadata:
      labels:
        app: dnsomatic
    spec:
      containers:
        - name: dnsomatic
          image: ammmze/dns-o-matic
          env:
            - name: DELAY
              value: "5m"
            - name: IP_ADDR_PROVIDER
              value: "https://api.ipify.org"
          envFrom:
            - secretRef:
                name: dnsomatic-credentials
