apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumble
  labels:
    app: mumble
spec:
  selector:
    matchLabels:
      app: mumble
  template:
    metadata:
      labels:
        app: mumble
    spec:
      containers:
        - name: mumble
          image: mumblevoip/mumble-server
          envFrom:
            - configMapRef:
                name: mumble-config-map
          ports:
            - containerPort: 64738
              protocol: TCP
            - containerPort: 64738
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mumble-data-pvc
