apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumble
  labels:
    app: mumble
spec:
  selector:
    matchLabels:
      app: mumble
  template:
    metadata:
      labels:
        app: mumble
    spec:
      initContainers:
        - name: config-data
          image: debian
          command: ["/bin/sh", "-c"]
          args: ["apt update; apt install -y rsync openssh-client; rsync -vr rancher@192.168.0.112:/home/rancher/docker-vulcanus/murmur/data/* /config/; chown -R 1000:1000 /config"]
          volumeMounts:
            - mountPath: /config
              name: config
            - name: rancher-key
              mountPath: /root/.ssh/
              readOnly: true
      # TODO: can the murmur.ini be a configmap?
      containers:
        - name: mumble
          image: mumblevoip/mumble-server
          ports:
            - containerPort: 64738
              protocol: TCP
            - containerPort: 64738
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: mumble-config-pvc
        - name: rancher-key
          secret:
            secretName: rancher-key
            defaultMode: 0400
            items:
              - key: ssh-privatekey
                path: id_rsa
              - key: ssh-publickey
                path: id_rsa.pub
              - key: known_hosts
                path: known_hosts
