apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumble
  labels:
    app: mumble
spec:
  selector:
    matchLabels:
      app: mumble
  template:
    metadata:
      labels:
        app: mumble
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R 10000:10000 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: mumble
          image: mumblevoip/mumble-server:v1.5.735 # {"$imagepolicy": "apps:mumble"}
          envFrom:
            - configMapRef:
                name: mumble-config-map
          ports:
            - containerPort: 64738
              protocol: TCP
            - containerPort: 64738
              protocol: UDP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mumble-data-pvc
