apiVersion: v1
kind: Service
metadata:
  name: mumble
spec:
  selector:
    app: mumble
  ports:
    - name: mumble-tcp
      protocol: TCP
      port: 64738
    - name: mumble-udp
      protocol: UDP
      port: 64738
