apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: photoprism
spec:
  image: photoprism/photoprism
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: photoprism
spec:
  imageRepositoryRef:
    name: photoprism
  filterTags:
    pattern: '^(?P<version>[0-9]+)$'
    extract: '$version'
  policy:
    numerical:
      order: asc
