apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    public: "true"
spec:
  tls:
    - hosts:
        - photoprism.immortalkeep.com
      secretName: photoprism-ingress-tls
  rules:
  - host: photoprism.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: photoprism
            port:
              number: 2342
