apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-gateway-credentials
stringData:
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:/O1cmG90E+o98W+2eWgXHmDGFUZlWHN812ruIawS0GY=,iv:8H4Qp5qJZqxLDWvgH5yQBK9sQ8v41d+ReSq1M3iO5jM=,tag:6hKgf9pHoXl5IbfMlSBtjA==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:iVQl4TQJLxVq2YEh3ZKe6//z/nB5WVFpMNWmA1Mx6b3z+RmRNZsuP09DNuC5+4TUg2/Kv18=,iv:iMYRZdA2sLqgqmjL+mpNT5nYdLRR4dyN3mTNhwh5Em0=,tag:1ccm0ytkGDtLXLkKkswFpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBzUHNt
            Nk9aSVFsY25xWnEvWWZYUFlrbmZjdVc3WHdhOEdNMU1SRkhUa0h3Ckt6akJEQmtt
            ZCtESnNUeWtWdFhxb0xsM1hQQWRDQmFoblY4N1k4NXg2dEUKLS0tIFlGdTJQVTVu
            TXZwWmJpYlk3cTU4SmxXR3V6cjFoNnp3OGp3eHVFOStFTDQKR8y6gpSW5KRMOw7f
            CESo3rI7iHp0tWjI5Dl/0fL/wSlaWJmu3OIcQ4YMh/eV8oCIJXe9NoKB0YlotuOA
            jvzo5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBhdVo0
            TW16SzVTbGhPRzAwYW5xZkYybW9CcTBieG5UTEZOcFh3ajRzalVRCnpMdzExQW9w
            RXM0aWlnczRacGMzV29LWnAydjdGUER1MmdDMzA1Um8vcm8KLS0tIDZ0WjZVWWRr
            ZlF5dHVVczQ2Ym1Galh6QURvT09BYWRldm1aY1pGVzlRK28KDGkEeHNOk1vcM640
            q7BBTFfc9e7L1Ujdje2fR9r0SLw2dQkna5jRoJaeOHrTBDRCvRUCpW3luY4umxrP
            IgHRag==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVGF4RUdwZHJvR3k1QU5C
            NUVkZlE0ekJISXpIMDFpbTZIL3hIc0JSL2h3ClFzYWxBNkZ3Q3hSOTdRMUtnUGIr
            Q1Y1UHhla3NETmFFNVdOY25NWG8xUEEKLS0tIGE3ZWRDRHAycHg3MGlGcExlMFNN
            NTNOK3QyZFRDd0RteWVVZWp4VUEyb00KqVk7fbSzmO2i0D16/mS9NL5MCakO9py7
            6lpVuTBKr0sJUgyWNdyy12RS3n9gGyF5++/Q5ki18FYHGUze4ZOb9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T04:06:49Z"
    mac: ENC[AES256_GCM,data:ToRH3Gza8oSNI128m21t7ymE+xmOiHvHekSQT8dws5jyzCmKtb+lDwI8COLZRfjaCbFDvc3Mp3BNkMb7XYYLk4F6NJJ1ddNcxI4gyKAwre0jXkVzfI1Cvx379Uzcyhnjr/BZ8qmIsbRhFHQOY0NFH6NsNqqALyn6IZBOjt/J8uA=,iv:u26KoI+b7TErrjua1boQAdRy7HtFmpi6fdfq+oRgy/E=,tag:Hzfb74WrIID3LMF5UE6Uhg==,type:str]
    version: 3.13.1
