apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: speedtest-tracker
spec:
  image: lscr.io/linuxserver/speedtest-tracker
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: speedtest-tracker
spec:
  imageRepositoryRef:
    name: speedtest-tracker
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=1.14.0'
