apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:ve6dxoNgM1CtJgstfX4dTEdSvCS6wpNF/77whGbvovPVBeJm4pnC8gGHdpadPVQ4Eabu,iv:jLHr6bTZkDl6mAm02IWHasbyTiRn6Ph/q3lHmRyrSnA=,tag:YXe9kfPx/7gG1IjnF0geiw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSB1dnU1
            RVpwOVhoVk5BMHdrZ1RjZUo5U29qNDZNS1ZTNzJ6WmU5N0h1dXpzCjZzSG9tcFVS
            MzJPbG04dzUxYkcyNlJCS1AvVnBYR2Y0dXlIbi94dWF1amsKLS0tIHZMbUpYN0RS
            Z0pTd216ZlpJSWh4d2dmTUlTLy9RY3BucE1iTDhpZ3d4dHcKKljqRFGdPfWyNPB7
            1hlla46XRekxIwCjPeKO1IohDowyFh/sdjfqTE6vYGcMU9jA59cODEV+R5YPEKS/
            6Q4h2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBuUXBH
            ZFQzbVdLQjZMVmpCS3Y1akxzRXhJMXg1ZUIvSFdKRmRrY2IzMFVZClVGZ2RSc0ZC
            QzhvOTVwS2ViTklXSHh4YjZqVWxydU92L2dVOEdLaTNlTlkKLS0tIDZCZnBPc0Nj
            SUlPSXh0b0dRRnU2SnVUclVOSlBnUlZDWnY0U3JXL1NLRTQKXr/cpK1pdw2KoOtY
            JJHBJdAaaTZSoZj6ZKbVONcUjZq55a3RQXcqnhNRnEEej9PbWuNXiUdrTmbEX4Pb
            YGA6Zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TlA5b2RPVXlMMzE0YS82
            RCtoNitMWml2Q3djRkxyMXJieUpldEJJdlRZCmIvWkxNWDVaZE5VSWNRS3liQmRx
            QmQ1c2hGNis4VXBtcVFLN29mTS9RNEkKLS0tIE80c2FXWXBvSjVTNXk5TTViS212
            cm91TGx3T3BzZGdtUWNaendJN1g1WTgKBDcsXysVQpJaDyos7ubKkq0m9zbOeN8S
            /5MgepKhT1SYMKmPmFe8IbslqR0JF66mBVDBaCaYYonXOlOhGhoMDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T04:05:34Z"
    mac: ENC[AES256_GCM,data:XXF5zNjeTUqzs0IPYWd8xO0RLj2+79ygdc1SwjXL5No9R8XMPAQRzsUIcy9fy40XnVT/aLZXCEv6fj4i8TXpCfBCeTrYF1wFjJ/3PiiSv6mO78WYWEfC2iG6vM/WNkgTM9I0VtXEhnl8zxefNdkQSF46l7FPVwK1B3heRp6sJoM=,iv:2+Cd/l2HogkyVvLy7n8n4Z6sOFjlaDjtYaLb7IKOjew=,tag:Hi3KSndzVqMMtNDrLrhLDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
