apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automatic-ripping-machine-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
