kind: ConfigMap
apiVersion: v1
metadata:
  name: automatic-ripping-machine-init-scripts
data:
  arm_user_files_setup.sh: |
    #!/bin/bash
    # This script is first to run due to this: https://github.com/phusion/baseimage-docker#running_startup_scripts.
    set -euo pipefail

    export ARM_HOME="/home/root"

    echo "Adding users to 'render' group"
    usermod -a -G render arm
    usermod -a -G render root

    ### Setup Files

    # symlink for the arm.log file
    touch /home/root/logs/arm.log
    ln -s /home/root/logs/arm.log /home/arm/logs/arm.log

    # setup needed/expected dirs if not found
    SUBDIRS="media/completed media/raw media/movies media/transcode logs/progress .MakeMKV"
    for dir in $SUBDIRS ; do
        thisDir="$ARM_HOME/$dir"
        if [[ ! -d "$thisDir" ]] ; then
            echo "Creating dir: $thisDir"
            mkdir -p "$thisDir"
        fi
    done

    # abcde.conf is expected in /etc by the abcde installation
    cp --no-clobber /opt/arm/setup/.abcde.conf /etc/arm/config/abcde.conf
    ln -sf /etc/arm/config/abcde.conf /etc/abcde.conf

  51-docker-arm.rules: |
    # ID_CDROM_MEDIA_BD = Bluray
    # ID_CDROM_MEDIA_DVD = DVD
    # ID_CDROM_MEDIA_CD = CD
    ACTION=="change", SUBSYSTEM=="block", RUN+="/opt/arm/scripts/docker/docker_arm_wrapper.sh %k"

  armui.sh: |
    #!/bin/bash
    echo "Starting web ui"
    chmod +x /opt/arm/arm/runui.py
    exec /bin/python3 /opt/arm/arm/runui.py
