apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-dropbox-bisync-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
