apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-dropbox
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "0/15 * * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: config-data
              # Bootstrap the dropbox config/token the very first time, using a secret.
              #
              # On a local machine, log into dropbox using `rclone config`
              # and then copy those config values to `rclone-conf-secret.yaml`.
              #
              # This does mean that if changes are made to the rclone.conf config,
              # you'll need to drop the `rclone-dropbox-config` PV in Kubernetes.
              image: busybox:latest
              command: ["cp", "--no-clobber", "/config/rclone.conf", "/data/rclone.conf"]
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
                - mountPath: /data
                  name: config-data
          containers:
            - name: rclone
              image: rclone/rclone:1.69.1 # {"$imagepolicy": "apps:rclone"}
              args:
                - "bisync"
                - "/dropbox/"
                - "$(DROPBOX_PATH)"
                - "--metadata"
                - "--verbose"
                - "--create-empty-src-dirs"
                - "--fix-case"
                - "--compare=size,modtime,checksum"
                - "--slow-hash-sync-only"
                - "--resilient"
                - "--recover"
                - "--max-lock=6h"
                #- "--resync"  # For the first real run, run it with "resync". Creates a superset of both sides files, and a `.cache` directory. After that remove this flag.
                #- "--dry-run"  # Initially run it with dry-run to check that things work.
              env:
                - name: DROPBOX_PATH
                  valueFrom:
                    secretKeyRef:
                      name: rclone-config
                      key: dropbox-path
              volumeMounts:
                - name: bisync-cache
                  mountPath: /root/.cache/rclone/
                - name: config-data
                  mountPath: /config/rclone/
                - name: syncthing
                  mountPath: /dropbox
                  subPath: dropbox/
          restartPolicy: OnFailure
          volumes:
            - name: config
              secret:
                secretName: rclone-config
                items:
                  - key: conf
                    path: rclone.conf
            - name: bisync-cache
              # Rclone needs to keep track of the files on each side, using this persistent cache.
              persistentVolumeClaim:
                claimName: rclone-dropbox-bisync-cache-pvc
            - name: config-data
              # Dropbox needs the rclone config file to be writeable, so that it can refresh the access token
              persistentVolumeClaim:
                claimName: rclone-dropbox-config-pvc
            - name: syncthing
              persistentVolumeClaim:
                claimName: syncthing-pvc
