apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-dropbox-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: openebs-hostpath
