apiVersion: v1
kind: Secret
metadata:
    name: rustdesk
type: Opaque
stringData:
    KEY: ENC[AES256_GCM,data:c2bndCP/ZzDib/xi31d5qXh2ar9K/1Xdgspe9XktLpINagEAARxTwT6EF4qHeg3VXFFzLIQx8gaB/ILkdiFM1JK5rPqOwAK/JsUg/PyoSYQFChv3fGc1mQ==,iv:BVwTO1NfTW1th1LbxoHxDWwER8+cqxjl+ZskfqtGXP8=,tag:7b3c3KDuQ0yX8RmyJmffKA==,type:str]
    KEY_PUB: ENC[AES256_GCM,data:/uz2RxgmVSqBPhF56JV1nSKxyrHHXxPC7YJ1ixLM1pFk3C7QcolYRK81l2c=,iv:EeyFyJ8Yx6hBd4HiyX6/Y40pKw2mGQ0kIJI03/ekMdI=,tag:I6R3t0+1Tm0pCqKZy0V+gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBzWTJC
            WDlsdk8xREoxbXl4QVhSWjFkeDhQczM5SUp0MHdMTEU2WjV6UXhRCmRyNGFrUE1Z
            dGswVmNkaFJYNHcxc09zUmY3OEg5TlpRSERpS2tid3p1aDQKLS0tIFliejlURkVY
            SHBCUWF5UU56WUFvWDhDZXhMZGFFNlVnTDdIQjBzYWwydXcKmEUHKA9nj/odcwhq
            4p4qZy8ldFFR9Y0oyPr2Jen00vx8gOR5r6UKFDep1Lcj6Rym9TzxxEpsvVKnWiEb
            v4Ux6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBmcDkr
            Z3VNcTVMd0pOYVZ3UWZxV0FneU51c1k3SWt0ZlAxemRsaDRPblNFCmt1WTBNcmxR
            Qzl5OVNjYWRYeVdHb3NJWFMxeGxtSFZPamJJZllYdEpRbk0KLS0tIC9yS3hicWYy
            MlB0U1A2a1JUOUhQUURSUkdERjZmTVNLMitBM2hyRVZRVnMK9njqiYZ8JAiPnO9l
            JU91Q8Qx1J/mO9y2OGKuIfbGiP+KGqVuAPqqmV9CaxI/pXs8zaccU4qQe0L4Hfit
            fXJoow==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaFU3S0xJWG9hT1hNSCtY
            eHM4cXBuZlA4UGFEd3hNd0tYVERlbXJLN2lRCnNJbFBVZEVJUjhkSUhoanVDWEN6
            endVVlRKZjY1eVhRTTdnT041MFlHYm8KLS0tIG10eDRnVFFUbHJHWXp0NmNsQmEy
            ZGgzZ3R2cCttOWVyWFd5VmdONmpMY1kKTMyYXGw7USWTtltA4t4QXC+zsqrX7qtB
            5d9Lro3Ku7dImkQfP5823oqQkq+mJE1iNMe8ZWPQuVzLIUbQVmeSmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T02:49:41Z"
    mac: ENC[AES256_GCM,data:QZWLhU/43xXx95tr86655vqLcLaLb2iZtwJ17uxtgfVpVIJSYpqOW5H5NSRyiiJpyXLjYsQdHG+Lg1OhuI1iCxHsiO7irQcJYW5yuxPtx8FQ5PEuFhHHMKgFwPQwIk9q0YBA71QjMDhgwsoU3wa6eXg0CsQKsciRYHFTLHh5RnQ=,iv:3y3hXoRFETt5k1WmvPl5k3Gu4HG5a4nlse0MNMsiRGE=,tag:yPNpHL5wH1q0QEr4FMFD7A==,type:str]
    version: 3.13.1
