apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2026-03-29T05:49:00Z"
    name: trello-randomizer
stringData:
    TRELLO_API_KEY: ENC[AES256_GCM,data:skKUmoKCZ2OR23v/AcQc36KrrzVfQ37h0fvhZVn0lsU=,iv:DVzLCok+gEo2GFmYmgvlHRW5fyHDM+Vmf6skbbPkm0A=,tag:kmXsfLwylhSnQupOTxoAqQ==,type:str]
    TRELLO_TOKEN: ENC[AES256_GCM,data:cEX9YuvEtYQQrpI9CMWR7EYYk6JOeeTuhN7naTH9OkCrxUyMHcWaiuOHSxjECLzhWAUb5Qr2i+/Bbs7nMz4TeT2t4iem1Ue/XRUFFA==,iv:YWos1nNCizRRShM3ZXyICfWfT/AGdcmsm2AQa7OGixY=,tag:p57DWQiGhqoLKQww318vuA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBqUzlT
            NDhzYUQrVG9WaWUzNzFkb3UrcG1TdllNQVdXRFhScDVTYlRGRGxrCmtrWFQySndS
            MnRwU2g4Y2dXWThkeE1XWk9MYjJ3ZXlLQnF3WkR5alZQYVEKLS0tIEZCS3g2bk9s
            MTdQNDNRQ2tyOGhMK05GQ3dVTW1vZ1BpeEpxOGNUQUZlaDgKITfhg/ie8Xzbine1
            E4QcL07BVw0XRYH8iaoV2vkr033llGN8Qj7qHlRyuscX5Z/TxR+xX6j2P3IaYK3H
            t6FHrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSA5UUNF
            QlRQOVUxeDlsbGxRd1hFTS8rbWREZTg3dmxvY1BUU2dCMTRuQzNjCjQyTXVGUUIw
            Vk9mQmpYTGtqaVAwMWtoTWhaUld1ejF4YVFlb2FSV3VhTjQKLS0tIHQ1bWpINGNK
            Z1RyR3ZuOTMwYjkyZ1I2RUZyTEZpVUpvMGdJdXpKbmhwbEEKBC4iu/uz/p+BhrgE
            esU50+vhVKg5Bc2Tf/ez5cWsAtlEOsiSHhbLQ6lhS3Z4E3HNr7A7Zdv+JhoCHdRb
            EtBGKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYVlZa0ZPRFRpWkhJMldY
            Q3pFejh0TmFXbUlES0g4S1NYV0xrTXRmRTJ3CmJiUTh4WlZ5eUY0Zk0yeHpxMVFt
            SlZPQWhrZUE4VC9XM0VJV1BUazZWU2MKLS0tIHBQSHR4c2R1eERqd29Gdk9ZOGRp
            cUNxeDhqNm1BSTZhRi9hYnZwS1dQL2MKozD1Tguec7PZe2XtEtDqYAEgiToB5jEl
            TmnlMiJg6YsWO6RvxIJ7by5CJmIevndP3Ql4+bO0fHt6lY2MoSqyOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T05:50:09Z"
    mac: ENC[AES256_GCM,data:Tiklq9ft2m90zKlmHNQrIqh2yRKr4IWmx9IP+9yTPfPR/ZhpUtNvTcbxN529BArgAcQN/xwJjso37+8RhCrHkEtr3e1Ti24Vsj6rs3N/6uegO61HRR5iMPBbvv1uCzy2KZKqpvOyDgp4MnBr8Y+61c/Bd2qfKUv8RZYz6wOz7HU=,iv:zQ7gMSmjCA7W6RTS5ZTJwFz2P9QB4fjG3V74CvKWRAE=,tag:BCkbvSXbAwO0Sjn8xmr8vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
