apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: audio-pv
    volumeAttributes:
      source: "//192.168.1.105/media/audio"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: infrastructure
  mountOptions:
    - rw
  volumeMode: Filesystem
