apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: audio-pv
    volumeAttributes:
      source: "//192.168.0.105/media/audio"
    #nodeStageSecretRef:
    #  name: smbcreds
    #  namespace: infrastructure
  mountOptions:
    - rw
    - guest
    #- uid=1000
    #- gid=1100
  volumeMode: Filesystem
