apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    creationTimestamp: null
    name: docker-credentials
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:SNutwssOTmGUwhdxhVbNMMcqL97cC8Cgqoh6979rIlPXVFP90aMvE7CO0Mb8aVrQHp6zlzP79o0Ordfe/xZKOzWywnKhPZWJbaGkAwa0q2btN24evu+v2X6WjIwkjp90cX69syRgIWBXzUYR7SJdRqdTYtBKcDNfiANpjBqvz77gplfzhGkGthdqyiGlWMe20JRY/+nrDM2iCtxN3upbZ7i91CQAavPegXNKbp8/JI6dxYJ1ktS5T9wVH95ywClJjrceXZfu9RM8KEZ34slIFsIc/T7bxP0bErQd1Ff7lt/d,iv:ujIh2/lRJz8OWR2yFUIGoMsYMntL5TpK0i/z7T0FKmM=,tag:ulGh30Liu58Q661txdFtTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMGhNaE1xV3RXOGJqR2lN
            cmVqT3FaYUpPZEsrdFg0WERaSXNVYTV1dkRrCmNBWWxCRkJBbFJUdzVhZGpvZmd1
            aFhlRStBdTdpM2VRdjZQOXpHWlZFZG8KLS0tIHRsRkp6bGVadjJJZ2VpKzdEN01T
            cHZHWmplNzdFK3E2QXdJby9adERKNDAK0ahfd8TD1j2FhLF8WzrEwJMHgMgB7A/G
            DO8bTjWMAq4mgvd9oJGokdXzCsijX6sBsAULjgjBDqWrMTnkNMenzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T17:30:34Z"
    mac: ENC[AES256_GCM,data:PtH+IDR7MA5o6hBn0VfqILMwN/Nms+6BXYRT34qhjYZMQt3LCKXlHEFsdpnTIvCCYINxRTuK2uAQWmuxm5UZtPi6/E1ggkTYQPmZY5rtelIVPVYqXCMzWXNBl9iyFTzCeuqOy0Cz8ksGcMD3v2N3JpkIEKL/YoQJn280Yzf5oIw=,iv:TbhYDixgwvT/377d0HPkpY6YjQAEReRv1l7ERr36sL4=,tag:5yxlRx8wNz/EwN3kxM/ksg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
