apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
stringData:
    admin-user: ENC[AES256_GCM,data:v5f6UCk=,iv:kffoAdHXnUjPU6uRVWM5SR4D6RwmvNuZQ6eaGh/P5PA=,tag:Fm3P+8qmrqS5Ei3WMhvneA==,type:str]
    admin-password: ENC[AES256_GCM,data:/OaHHATIqgnDy4TedoxpYhUKG5dA+FP49fS6+mA4DvY=,iv:uYKbpxg2atbIdqV+KNMzUz9SSLWKOT2oTdonnD39Z6Y=,tag:XukzligV+VsKrv8zbnXOLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBIc0pG
            TkNlRUNwU3pjNmlBY2x1bXlYNEo4TFJSMkJ0S2QvVlhOTnZaSDJvCmVyR1VvOVc4
            RGwzSGFraHhVZGdDYXFNYkd2aWE1SExWUVlYVDlXYTRLNkkKLS0tICs2Q3U3OUFP
            RG9UcEJyMnZOVDRzdnJHOW0vdVVVR09BbHdNT0IrM1psek0KKf00w/gA03Eui57E
            qxJPI8HhgvFDUxzYFKkdzcdKGKWBaHz9No78arRr50CzKgAmk2wbAlr9+7sVa3MM
            emmY5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBmdzVW
            NlNMZ1RoVExxUE9TR3NEUVVIVjFWUy81bGZhSXpXaFNnZm9URndJCmRrM3NKYzRq
            a3pvb1pGUnZnbXgrV2tySUxEeENsTzZVK1ZTZFdTOW8yaE0KLS0tIEdPN3Avekh3
            Y0dRdDZhSnkxQm1PYUdiZHMxQ2ZSL0hvNFljZ3hmVW9pQ1kKJbhHy7wsohi9YTjv
            TjjKjxchXqHvW+alcjELUa6mABlfOrbGLLBFY1NP00zMENp+/SBfAtQaGx2BXTGJ
            SqWJ+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSHRNVk5BeXVvMHVhMW5r
            TlpORGRnTXA4ZUtMWTROYjJjYjBxQ2ZNVXhjCnBBRHN3QXF0M2lZVEJzemoyZlJ4
            SkloV0ZEQmVnT1NnUC9ZNjBqeFI1MlEKLS0tIHVyTitiWFNHcThGZlo4aHlPSE12
            akRWODhGbnRIVzdBdXYzVG9rakxIOHMKpgVdb8GazK4faoJE5qwu5y1UerjLmgdL
            GaGMnQR4Ga8l1k114s5nUUyOaxvYuJNjbAP8Z42O7oI4K9evHvkvEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T03:10:45Z"
    mac: ENC[AES256_GCM,data:+bX8XjiUtA1fJDaUwsqwRmIbM9zGTFGc4ne1y57uCUfqhdWgRSKvbucizVvuxTpvz+0Jxu3Q4irDkH4ayip3ZxpL8t8IvcMh+iqiKvZKk0n2lV47MffvM22sEHLu42G08uvELzfApwWWtMWP0Q3Q9T3MyW/XMuNi3RphGQCVwBE=,iv:wUQQzvlYI1kLWT8DJaqqecD2O3umszhQhkKSrW14mVY=,tag:ur/86PTuoL70U5hUzYTxAw==,type:str]
    version: 3.13.1
