apiVersion: kustomize.config.k8s.io/v1beta1
# TODO: there's a v1beta2 version
kind: Kustomization
namespace: infrastructure
resources:
  - audio-pv.yaml
  - openebs.yaml
  - namespace.yaml
  - sources
  - traefik
  # TODO:
  # How do we set flux to install infrastructure before apps?
  # Push this whole thing to the repo and watch what flux does with it.  First time success?
