apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - audio-pv.yaml
  - basic-auth.yaml
  - borg-backups-pv.yaml
  - coredns.yaml
  - csi-driver-smb.yaml
  - games-pv.yaml
  - kubernetes-dashboard.yaml
  - metallb.yaml
  - namespace.yaml
  - openebs.yaml
  - openvpn
  - photos-pv.yaml
  - prometheus.yaml
  - rancher-key.yaml
  - smb-credentials.yaml
  - syncthing-pv.yaml
  - traefik.yaml
  - traefik-internal.yaml
  - video-pv.yaml
