apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 15m  # 24h
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    deploymentMode: SingleBinary<->SimpleScalable
    loki:
      auth_enabled: false
      isDefault: false
      limits_config:
        retention_period: 30d
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
      persistence:
        storageClass: openebs-hostpath
    compactor:
      #compaction_interval: 1h
      #retention_delete_delay: 2h
      delete_request_store: filesystem
      retention_enabled: true
      working_directory: /var/loki/compactor


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.11.5
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
