apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 15m  # 24h
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.8.4
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    loki:
      auth_enabled: false
      isDefault: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
      persistence:
        storageClass: openebs-hostpath

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.11.5
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    #config:
    #  clients:
    #    - http://loki-gateway/loki/api/v1/push
    serviceMonitor:
      enabled: true
