apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Ti
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: media-pv
    volumeAttributes:
      source: "//192.168.0.105/media"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: infrastructure
  mountOptions:
    - rw
  volumeMode: Filesystem
