apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
spec:
  interval: 5m  # 24h
  url: https://openebs.github.io/charts


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 5m


---
# Not entirely sure this works, or what order it's applied in, but the Talos docs suggest it necessary
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: openebs-jiva-csi-iscsiadm
#data:
#  iscsiadm: |
#    #!/bin/sh
#    iscsid_pid=$(pgrep iscsid)
#
#    nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@" 
