apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
spec:
  interval: 24h
  url: https://openebs.github.io/charts


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    resources:
      # TODO: https://github.com/openebs/node-disk-manager/issues/673
      limits:
        cpu: 200m
      requests:
        cpu: 200m
  #  # https://github.com/openebs/charts/issues/324
  #  ndmExporter:
  #    enabled: true


---
# Not entirely sure this works, or what order it's applied in, but the Talos docs suggest it necessary
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: openebs-jiva-csi-iscsiadm
#data:
#  iscsiadm: |
#    #!/bin/sh
#    iscsid_pid=$(pgrep iscsid)
#
#    nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@" 
