apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 15m  # 24h
  url: https://prometheus-community.github.io/helm-charts
  #type: oci
  #url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:latest # {"$imagepolicy": "infrastructure:kube-prometheus"}

#---
#apiVersion: image.toolkit.fluxcd.io/v1beta2
#kind: ImageRepository
#metadata:
#  name: kube-prometheus
#spec:
#  image: ghcr.io/prometheus-community/charts/kube-prometheus-stack
#  interval: 15m0s
#
#---
#apiVersion: image.toolkit.fluxcd.io/v1beta2
#kind: ImagePolicy
#metadata:
#  name: kube-prometheus
#spec:
#  imageRepositoryRef:
#    name: kube-prometheus
#  filterTags:
#    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
#    extract: '$version'
#  policy:
#    semver:
#      range: '>=47.0.0'

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 50.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      #verify:
      #  provider: cosign
      interval: 60m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
    grafana:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - grafana.immortalkeep.com
        tls:
          - hosts:
              - grafana.immortalkeep.com
            secretName: prometheus-grafana-ingress-tls
    prometheus:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - prometheus.immortalkeep.com
        tls:
          - hosts:
              - prometheus.immortalkeep.com
            secretName: prometheus-ingress-tls
      prometheusSpec:
        retention: 30d
        #resources:
        #  requests:
        #    cpu: 200m
        #    memory: 200Mi
        ruleSelector: {}
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector: {}
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: {}
        probeSelector: {}
        probeSelectorNilUsesHelmValues: false
        probeNamespaceSelector: {}
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: prometheus-pvc
            spec:
              storageClassName: openebs-hostpath
              accessModes:
                - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi

---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grafana
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: flux-system

---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: grafana
spec:
  type: grafana
  address: "http://kube-prometheus-stack-grafana.monitoring/api/annotations"
  secretRef:
    name: grafana-auth
