apiVersion: pod-security.admission.config.k8s.io/v1alpha1
kind: PodSecurityConfiguration
defaults:
  audit: restricted
  audit-version: latest
  enforce: baseline
  enforce-version: latest
  warn: restricted
  warn-version: latest
exemptions:
  namespaces: [kube-system, openebs]
  usernames: []
  runtimeClasses: []
