apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: syncthing-pv
    volumeAttributes:
      source: "//192.168.0.105/filesync/syncthing"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: infrastructure
  mountOptions:
    - rw
  volumeMode: Filesystem
