apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 5m
  values:
    additionalArguments:
      - "--providers.docker.endpoint=tcp://192.168.0.112:2375"
      # TODO: why isn't the exposedbydefault working?
      - "--providers.docker.exposedByDefault=false"
    certResolvers:
      # TODO: can this resolver be made the default for all websecure connections?
      # TODO: change this to "letsencrypt" and in the docker-compose to match
      myresolver:
        acme:
          email: willy@weiskopf.me
          tlsChallenge: true
          storage: /data/acme.json
          #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
    persistence:
      enabled: true
      storageClass: openebs-hostpath
    ports:
      # TODO: these are not working for creating the entryPoints
      sftp:
        expose: true
        exposedPort: 2022
        port: 2022
        protocol: TCP
      web:
        redirectTo: websecure
      webdav:
        expose: true
        exposedPort: 10080
        port: 10080
        protocol: TCP


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    # TODO: do better than this hard-coded host.  Docs recommend something like traefik.localhost.  That might require a network DNS server or somesuch
    - match: Host(`192.168.0.201`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
