apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: soft-serve
spec:
  image: charmcli/soft-serve
  interval: 24h

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: soft-serve
spec:
  imageRepositoryRef:
    name: soft-serve
  filterTags:
    pattern: '^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=0.12.2 <1.0.0'

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: soft-serve-python
spec:
  image: python
  interval: 24h

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: soft-serve-python
spec:
  imageRepositoryRef:
    name: soft-serve-python
  filterTags:
    pattern: '^(?P<version>3\.[0-9]+\.[0-9]+)-alpine$'
    extract: '$version'
  policy:
    semver:
      range: '>=3.14.7 <4.0.0'
