apiVersion: v1
kind: Secret
metadata:
    name: soft-serve
type: Opaque
stringData:
    initial-admin-keys: ENC[AES256_GCM,data:EejF6MiHvhi5Nno5zbmoIqLqyzYAmZwdlkv4WB2ZM4SIF2KMRTs5+G13PXB5ETo0xkbyuPoeSvPxK8zb249YmKJLml0a9bcDWSnt+/c2bDQAG5Ej1GMF4/t8MBC+l36KYQczDPX/HJkx4lbRV2jWAq8XYFlYE1uobLzpBGyebs5rhsw0+I3VIYGGXAcpkawC99INFAza1mWOqJGDqyuhY820sp77voAWTRgeA0spp4XBCXnY6pNy4FuevsYMsEIR7vhRyNwcUxlx2wzGsUwFRLhpA6y/uLwKqLMkbQUPkyM2UXoA3X04ouI7ZMqf1HyZshSpud88BJdISWpr9cvKrBX+Zt/1ASCGyD1DEyWx3ACLLoivTcN3oFCONg==,iv:/oiHOHXvTODEU1Kz8ktceAVARZRnZ0wv7j6GWH9APOA=,tag:Bugb+gyS9trV+Ak29eqqlA==,type:str]
    mirror-ssh-key: ENC[AES256_GCM,data:H6mIn83Qjr+5BeCtE18nL2UYQ6IC/ZwT8YYwkfRr+9sfLA2jUJPU+zf4+zWAWcOT1YNgE6UGT9B9omrRSTr4Tg6igG9neR3b2ogaD2tKYh66lwMUvSN8LG3XYYpsLH69xWoY/4UuUGp+aN9TILxgKyiMbuSjSiXwPUKj7owqiQlnXkIzxJTLIdNr+4QDyo0WM6gk0GtjzpmyQqPPsAwjMG2DV1fJY6XQkWM47F8jZ+aXdwNRO4hGyeM8xBdRmO5UW1IJVIZo2IzMu0MSCBs7z5XN86XJusv2yKRwhno6SB9ENkW1yszyN5Jbc2G30l/Y6665YaPmOWhpl/JNfN6i/ILk1Tc0UVAG9ykPtz03g6PSguHXJmBrOCryTLF0qT+z4KreuzU88fgKVh0K4N7k+p71oCufLp8J2smIFJfIzLSeCN9Q+GPg0dbMnHGhIc9W+Z706h4kBFyNnSjlgYeHnWCTrRyV9etAmbh6BpVce3qzMVtJlpDRVOK2ihonR23CYTaXafkA3StCbiQ1hjfpl5nclQOYBeR2y4O2,iv:GFNcLsPBzJ9TibYZx0g2x8Nx7keFvNFFaJw4erkjzy0=,tag:2bjSlIy2BvjiPG+ZzxttyA==,type:str]
    github-token: ENC[AES256_GCM,data:vdc+cMnFBkhA4HpSrdbTSJnktbYgiT3Ct4pUuZzZzCMN,iv:a773TL9HUaOiC3wpyAO37IR9Pw0smKN7wWXYlO5qrxs=,tag:JH7pwe+gy9v4kzp6TxyE2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSB2Rjh4
            MXFaZjNmYlBBTXpBdWRUcis0WEVmYUFoc1lvUFhjbWpCVlByelQ0CnBaTURITWs2
            RkMxakJWU0E5NXFldkN6ZlRnZVRzbGdLZ0ZkcFJhQmtGNXMKLS0tIEZEdnN1UkMy
            MmNxVXRjcFZ0V1N3Wit3S2lxY2NDRmNKdlFCSTBrSWhaWncKFadeAL5xJQp/arNt
            8++HTbcs2CLmrj7cNIfDhNEhZ/icmivsRXCnKXdUgFEDa1w3pVNwiC1eg4jnByCm
            de4H0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBjQWJz
            WkV0RFJVSHBqT0dodTNRa3Z5Y2EyNlBXTVlNSG54QTV5eExTd21BCmd0b2hJM1Vn
            emUrakZ2b1F5VWFScHQxc3RWU3BlSVg4K3NPZnlEK1QrM0kKLS0tIGJ4ejJmRjF1
            Q0ovSjd6aHJwR2tTQzZGQ2hEb0hReWpFK3VreS9lWWJkYlEK+EgHlh8ttB8nXTGl
            8IcvDsE4H4WmsFMcyvzkwGO2Jr4TE+gGm0vFm4qDZv03JNq8fZCXv2RUHEhCyPv2
            qyEj9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdnJucUxGbDFDcVQ0OXAy
            NWhTRTRDODluU0lqTlZSb0dXckxQaC8xOGhNCmZJeTBLc2RtRTBhZEhBVWFpM0hm
            YUdSR3lXenQvNnBjNmZRL1FTUTZKYkEKLS0tIDE1M1AwaWQrWSs2czFQOE1SQ2Z5
            Q2NTdnVKSWplK01mRGdjcmxzbTFuL00KSLcydE3ViGv4+8sP5z8uszDnj6LZfU5J
            vOCygfqpIgqa7+5qAnx/B9A22KnamioRH3TISPwX8dHrNJbySmBRVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T19:32:17Z"
    mac: ENC[AES256_GCM,data:Fhi3hiGsMqnyJhH//x/5OK6Z5dOj2BblqK2ot7BGR4jSLCagRO0FlSa+uM506HMcVRWmOdpG5+BsmIVRpRKNcJmDsuLr3VaB8jAK7XSGg4eZO+jB4JS3nWqdreWfTP5EVApUou18LXVB3cufgUNyAEIQJq1D434FAH/ho/ygmBw=,iv:NNaNrGIjLASFPdkPRWjK28TDusak5q+xbb11uEZDc/Y=,tag:y8KqkqPLEcr/aIPS4Wc+mg==,type:str]
    version: 3.13.3
