apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: openvpn-udp
  labels:
    public: "true"

spec:
  entryPoints:
    - openvpn-udp
  routes:
    - services:
      - name: openvpn
        port: 1194
