apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databaseSize }}
  storageClassName: openebs-hostpath
