apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheSize }}
  storageClassName: openebs-hostpath
