apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  {{ if .Values.public }}
  labels:
    public: "true"
  {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.name }}.immortalkeep.com
      secretName: {{ .Values.name }}-ingress-tls
  rules:
  - host: {{ .Values.name }}.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 2342
