apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beets-library-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: openebs-hostpath
