apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: media-toolkit-webtop
spec:
  image: dartagan/media-toolkit-webtop
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: media-toolkit-webtop
spec:
  imageRepositoryRef:
    name: media-toolkit-webtop
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=0.1.0'
