apiVersion: v1
kind: Service
metadata:
  name: tinyproxy
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30008
