apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
spec:
  image: plexinc/pms-docker
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<version>[0-9.]+)-[0-9a-f]+$'
    extract: '$version'
  policy:
    numerical:
      order: asc
