---
# Note: the fileserver must be completely recreated to add new mount points to it

- name: 'set up a fileserver'
  hosts: fileserver
  vars:
    samba_groups:
      - groupname: users
        gid: 1100
      - groupname: fileshare
        gid: 1200
    samba_users:
      - username: rancher
        password: rancher
        uid: 1100
        group: 1100
        groups: fileshare
      - username: nobody
        uid: 65534
        group: nogroup
        groups: nogroup,fileshare

  tasks:
    # - name: install nfs
    #   apt:
    #     name: nfs-kernel-server
    #     update_cache: yes
    #     state: present

    #- name: install nfs-ganesha
    #  apt:
    #    name: nfs-ganesha
    #    update_cache: yes
    #    state: present

    #- name: install nfs-ganesha-vfs
    #  apt:
    #    name: nfs-ganesha-vfs
    #    update_cache: yes
    #    state: present

    - name: install samba
      apt:
        name: samba
        update_cache: yes
        state: present

    - name: create samba groups
      ansible.builtin.group:
        name: "{{ item.groupname }}"
        gid: "{{ item.gid }}"
      with_items: "{{ samba_groups }}"
      loop_control:
        label: "{{ item.groupname }}"

    - name: create samba users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        create_home: false
        group: "{{ item.uid }}"
        groups: "{{ item.groups }}"
      with_items: "{{ samba_users }}"
      loop_control:
        label: "{{ item.username }}"

    - name: add users to samba
      with_items: "{{ samba_users }}"
      when: "'password' in item"
      shell: >
        (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
        || (echo '{{ item.password }}'; echo '{{ item.password }}')
        | smbpasswd -s -a {{ item.username }}
      register: smbpasswd
      changed_when: "'Added user' in smbpasswd.stdout"
      loop_control:
        label: "{{ item.username }}"

    #- name: create nfs configuration
    #  template:
    #    dest: /etc/ganesha/ganesha.conf
    #    src: ganesha.conf.j2
    #    owner: root
    #    group: root
    #    mode: '0600'
    #  notify: reload nfs config

    - name: create samba configuration
      template:
        dest: /etc/samba/smb.conf
        src: smb.conf.j2
        owner: root
        group: root
        mode: '0600'
      notify: reload samba config

   #- name: start nfs and enable on boot
   #  systemd:
   #    name: nfs-ganesha
   #    enabled: yes
   #    state: started

    - name: start samba and enable on boot
      systemd:
        name: smbd
        enabled: yes
        state: started

  handlers:
  # - name: reload nfs config
  #   shell: systemctl reload nfs-ganesha
  #   args:
  #     executable: /bin/bash

  - name: reload samba config
    shell: smbcontrol all reload-config
    args:
      executable: /bin/bash
