---
- name: 'configure RancherOS guest'
  hosts: rancheros
  become: yes
  vars:

  tasks:
    # Changes often require two restarts, one to add the cloud-config and one to run the config on start
    - name: cloud config
      template:
        dest: /home/rancher/cloud-config.yml
        src: rancheros-cloud-config.yml.j2
        validate: ros config validate -i %s
      notify: load cloud-config

  handlers:
    - name: load cloud-config
      command: sudo ros config merge -i /home/rancher/cloud-config.yml
