---
# proxmox and proxmox_kvm options
api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
api_host: proxmox
defaults:
  balloon: 1024
  cores: 1
  cpu: 'host'
  cpus: 1
  disk:
    ct: 8
  format: 'qcow2'
  memory:
    ct: 1024
    vm: 2048
  mounts: '{}'
  nameserver: '192.168.0.104'
  netif: '{"net0":"name=eth0,gw=192.168.0.1,bridge=vmbr0"}'
  onboot: true
  ostype: 'l26'
  pubkey: "{{ lookup('env', 'PUBLIC_KEY') }}"
  #scsihw: 'virtio-scsi-pci'
  searchdomain: "{{ lookup('env', 'DOMAIN') }}"
  storage:
    ct: 'local-zfs'
    vm: 'local-zfs'
  #virtio: '{"scsi0":"gluster:10,cache=writeback,discard=on"}'

ostemplate: 'local:vztmpl/ubuntu-21.10-standard_21.10-1_amd64.tar.gz'
#ostemplate: 'local:vztmpl/debian-10-standard_10.7-1_amd64.tar.gz'
#ostemplate: 'local:vztmpl/alpine-3.14-default_20210623_amd64.tar.xz'

cts:
  wireguard:
    vmid: 103
    node: vulcanus
    memory: 512
    swap: 0
    cores: 1
    netif: '{"net0":"name=eth0,ip=192.168.0.103/24,gw=192.168.0.1,bridge=vmbr0"}'
