apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
  labels:
    app: sftpgo
spec:
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      containers:
        - name: app
          image: drakkan/sftpgo:v2.6.2-distroless-slim # {"$imagepolicy": "apps:sftpgo"}
          env:
            - name: SFTPGO_WEBDAVD__BINDINGS__0__PORT
              value: "10080"
            - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
              value: "true"
            - name: SFTPGO_DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sftpgo-credentials
                  key: username
            - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sftpgo-credentials
                  key: password
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 2022
              protocol: TCP
            - containerPort: 10080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/sftpgo
              name: data
            - mountPath: /notes
              name: syncthing
              subPath: dropbox/notes
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sftpgo-pvc
        - name: syncthing
          persistentVolumeClaim:
            claimName: syncthing-pvc
