apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sftpgo
spec:
  image: drakkan/sftpgo
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sftpgo
spec:
  imageRepositoryRef:
    name: sftpgo
  filterTags:
    pattern: '^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-distroless-slim$'
    extract: '$version'
  policy:
    semver:
      range: '^2.0.0'
