apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - sftpgo.immortalkeep.com
      secretName: sftpgo-ingress-tls
  rules:
  - host: sftpgo.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: sftpgo
            port:
              number: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sftpgo-sftp
  labels:
    public: "true"
spec:
  entryPoints:
    - sftp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: sftpgo
          port: 2022

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sftpgo-webdav
  labels:
    public: "true"
spec:
  entryPoints:
    - webdav
  routes:
    - match: HostSNI(`*`)
      services:
        - name: sftpgo
          port: 10080
