apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: salamander
spec:
  releaseName: salamander
  chart:
    spec:
      chart: ./kubernetes/charts/photoprism
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: salamander
    image: photoprism/photoprism:260728 # {"$imagepolicy": "apps:salamander"}
    mariadbImage: mariadb:10.11.19 # {"$imagepolicy": "apps:salamander-mariadb"}
    originalsPath: salamander/originals
    importPath: salamander/import
