apiVersion: v1
kind: Secret
metadata:
    name: borgmatic-pushover
stringData:
    pushover-user-key: ENC[AES256_GCM,data:NmhLD6u8kA3vk2mMIVrsVeBtkk0Dtw/ZSdYt9GFL,iv:54W5ynd9FaYBk6NZKWVd6pOy05wlFrRXtU9pGvDbmhY=,tag:nIlRgV5sdaVD6bZYHcqQuQ==,type:str]
    pushover-token: ENC[AES256_GCM,data:pC9EgFD/GLqwWXbSnyEBLMaR+Mlz0QU1Mc+7EkD1,iv:9zJ2v5SsO1cA4iMWjRMtll/f/HvD35xKhKb7jFINdF4=,tag:Vgpy3heaILnIbPHvFkw/Vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBvbVB4
            TDUzZFF4SCtxL1MvYlBBS2Jlcy90SXI4NzNRd2JBSWVYTFErK1E0CmNTVks1eFpE
            bkVRV3BtendQSXpZTUMydkFHNlBybDNyZ0VHQTdXU3dOaTgKLS0tIHJXek1CVUNI
            ZWtnZ2lZNnJHRStIYytXM3c1cE1SL0Q3TGZQZURNempSZzAKyURamsJKhiOYqLro
            g6oChaNZ5MI7xm+xJOQTQ72pJycP8MEc6NuI10bSplBgeJ3pY2EzaM23kZCrmEZB
            0LCjNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBiN2RE
            b20rVFF1V0lGSmdZNHBzNlRoS2JMQ1I1MElzNWpTam9CZkk3WDBNCmRqWFhRNStu
            VzJ4V0pkTUdiMWd0SjROa2E5YndlV29aa0pBSTRVZi9XWW8KLS0tIFBsVTFaU2ZS
            OGJjaVljUHNTU04wZlVKZnhvRGMzbEZEeUFNejVHTWZaRjQKQlSLCUh1UC3khyYX
            KZflcHTBxYYcP0TbPf8tkVL6GKKhFM8SVRfnB9sRN4rs13drFHuX+HcjHDwdD3/9
            iZv2HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V2VwWENqTnlLeFJoQWRK
            SmJtcmJycHd2bVJ2NnNQUUxtc28wd040S3lJCjZHMUJFTDhMaE40ZVlPaTh1RGFW
            alRPd1YvSHZkdmNVcTdsM3pJckVZbWsKLS0tIGxmYllkSGxSM1dVampGdUNNc0I4
            VVUyaThIbHQ1eUZDd3FMV21Sd2lpUVEKDpzgmmGIZFv3neC76Ox5rlD2QjBuBnKG
            MM0wEjZjS78vN/KSqZ/jmO0V2fidMLmxYQMRUFkB2iL3ADvTkYAofg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T02:06:56Z"
    mac: ENC[AES256_GCM,data:zokDDtdl1kFijx6lxJOCwSZM05vmR8zKXhAOSTvclq/BcqfBMflNQqZa7dfivNq0hUUHhIkPhluWrboL1T3lPvt8K24ZryczqaYhJtGV0nYuqZvKvYQrJyX293GQEHbJE7ML7FM4yY3IpUgxMZ5EOER3fAgGvhrJEPi9xns43iI=,iv:EsBxXsWx5vaOQUg+fVm033X51xV24lHe00aUgXA01c0=,tag:wTlRzOpjV76gt8feTnzC0Q==,type:str]
    version: 3.13.1
