apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: linkding
spec:
  image: sissbruecker/linkding
  interval: 15m0s


---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linkding
spec:
  imageRepositoryRef:
    name: linkding
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-plus$'
    extract: '$version'
  policy:
    semver:
      range: '>=1.36.0'
