apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    cert-manager.io/clusterIssuer: letsencrypt
    #traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
  labels:
    public: "true"
spec:
  #ingressClassName: traefik
  tls:
    - hosts:
      - immortalkeep.com
      secretName: demo-ingress-tls
  rules:
  - host: immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: demo
            port:
              number: 8000
  - host: demo.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: demo
            port:
              number: 8000
