kind: ConfigMap
apiVersion: v1
metadata:
  name: podbook
data:
  nginx.conf: |
    server {
        root /var/www/;

        location / {
            try_files $uri @server;
        }

        location @server {
            proxy_set_header Host $host;
            proxy_pass http://localhost:5000;
        }
    }
