apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podbook
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-basic-auth@kubernetescrd
  labels:
    public: "true"
spec:
  tls:
    - hosts:
        - podbook.immortalkeep.com
      secretName: podbook-ingress-tls
  rules:
  - host: podbook2.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: podbook
            port:
              number: 80
