apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podbook
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-basic-auth@kubernetescrd
  labels:
    public: "true"
spec:
  rules:
  - host: podbook2.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: podbook
            port:
              number: 80
