apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:qIAjL18yCCY3WMTP+yBu1bviatywGmJtdy8DVTaQX1OMbNvImWKpVsqG8ttjN5985flMACg=,iv:VD6iLg3MipNnV0TM/auNC0hqGrnj/5HvABLVUcQUI6E=,tag:9R2Hnv05iM6liNQbzOwkWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBWMDV4
            cWpibjQzdHV4eEZNNXZ0c3dmVUswYzZYbWlhS3NzVzA4bzZwTTJjClhSa1BTSVU0
            RzVpVFhHNlZDN3FZRys5allDaDNGamdHNnV5YkZVa2RjYVkKLS0tIHAzRVAvVVUx
            NEIxSm1yTlZPRWlQT2pvNHJIZGlNUHkybDFJOEpHVzdoMkEKB04PunqUE/Psn9MM
            nL3jJGbW7RYpCfLWegBVHKRiBmMnyitbMr/L48uQ8hdJ3ug+zIsiQ27eS1Xvlo7d
            LWW04g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSA0bFBK
            eUNjZ3M5VzVJeDV4OUIvU1RCNkV6N2ZDWlZrejNJYVRGdkx5YW5ZCm55T3NqZzA3
            bXRkTTBVOGIxaHdQbFN2WTJ0RGxjdG80ODQ1OWtEOGVaZWcKLS0tIGVDUUdyZC9r
            bkZJR2htUkxVNGV5bG9PbEZGY0p1KzRVU0VMNXJsTStTTjAKE6OxGFXKy6VDc3F/
            dzvI16Nv3nmAwnLg6MrTLf6wS8J/iDNd4/KIpqsX/PeaFzmyzh/QgM2YU1mmpa3e
            fzgoQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtczZSQ0JIWnhFWjZCWm9D
            Qm85SXgzMDA3Nml2SVZROWFFVE5ZMnVOT0RRCk4raUwrZ05jS0NjR2RTbEtJVDh1
            eVA3YjNrcHJDRERxYlh2OFMwbFE2elUKLS0tIHdQY2NYcUhJNU1mOTRQd1pwYlJP
            OW9PL0NPNG5saWtsemtvWHZwa0JsZzAKrYEIi/FL3XLf/5/60uxAJSIivE6cJZa8
            mYsGS+3t0UNqTScizFZ4jmzNcWmoGTXVt6or1PbpKt0K8jBGXPwdRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T06:15:40Z"
    mac: ENC[AES256_GCM,data:8lRe8Fzxfm7hCBRagKcVEdWw6ImM/ef3E33GwX/Tv6/H83ApBW1Pxf4a5sG/46IdhEOCPHFhlVtepVNRAo86HfmmrV/+VofkgRpVLIUJWx8XKrYyBxXAXmYaDvNqpXsmDs7GuuMPOWwLsqmVFwTDAUy7F8w64176JXFybmCxJ6E=,iv:pBGUhI296FWvVcQ+0D8b4XGo5gnDKV7nVC7IY0qHBOo=,tag:fClIT52e9+B/t/fHnMxClQ==,type:str]
    version: 3.13.1
