apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: botamusique-mumble-cert
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - botamusique-mumble-cert.immortalkeep.com
      secretName: botamusique-mumble-tls
