apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podgrab
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-basic-auth@kubernetescrd
spec:
  rules:
  - host: podgrab.immortalkeep.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: podgrab
            port:
              number: 8080
